#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
# In betweeen every "I am alive" message it pauses for two seconds

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
