#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# displays username, user id and home directory path for the user

i="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$i"
